"""Mocked API Responses."""

COURSES_ENDPOINT_RESPONSE = {
    "count": 2,
    "next": None,
    "previous": None,
    "results": [
        {
            "key": "edX+DemoX",
            "uuid": "102c166f-af2b-4fe2-ade0-ab08063d4d40",
            "title": "Introduction to Computer Science",
            "course_runs": [
                {
                    "key": "course-v1:edX+DemoX+Demo_Course",
                    "uuid": "8db5692e-dfdd-4fe0-ba29-e30e793e6ae6",
                    "title": "Demonstration Course",
                    "external_key": None,
                    "image": None,
                    "short_description": "An introduction to the intellectual enterprises of computer science",
                    "marketing_url": "course/",
                    "seats": [
                        {
                            "type": "verified",
                            "price": "149.00",
                            "currency": "USD",
                            "upgrade_deadline": "2023-05-02T21:06:11.671090Z",
                            "upgrade_deadline_override": None,
                            "credit_provider": None,
                            "credit_hours": None,
                            "sku": "8CF08E5",
                            "bulk_sku": "A5B6DBE"
                        },
                        {
                            "type": "audit",
                            "price": "0.00",
                            "currency": "USD",
                            "upgrade_deadline": None,
                            "upgrade_deadline_override": None,
                            "credit_provider": None,
                            "credit_hours": None,
                            "sku": "68EFFFF",
                            "bulk_sku": None
                        }
                    ],
                    "start": "2013-02-05T05:00:00Z",
                    "end": "2023-10-31T11:49:41Z",
                    "go_live_date": None,
                    "enrollment_start": None,
                    "enrollment_end": "2022-12-31T11:49:58Z",
                    "weeks_to_complete": None,
                    "pacing_type": "instructor_paced",
                    "type": "verified",
                    "run_type": "2d598558-f94e-41f8-8829-01a0027d2d17",
                    "status": "published",
                    "is_enrollable": False,
                    "is_marketable": True,
                    "availability": "Current",
                    "course": "edX+DemoX",
                    "full_description": "This is CS50x , Harvard University's introduction to the ia",
                    "announcement": None,
                    "video": None,
                    "content_language": None,
                    "license": "",
                    "outcome": "",
                    "transcript_languages": [],
                    "instructors": [],
                    "staff": [],
                    "min_effort": None,
                    "max_effort": None,
                    "modified": "2023-05-22T18:02:32.723407Z",
                    "level_type": None,
                    "mobile_available": False,
                    "hidden": False,
                    "reporting_type": "mooc",
                    "eligible_for_financial_aid": True,
                    "first_enrollable_paid_seat_price": 149,
                    "has_ofac_restrictions": None,
                    "ofac_comment": "",
                    "enrollment_count": 0,
                    "recent_enrollment_count": 0,
                    "expected_program_type": None,
                    "expected_program_name": "",
                    "course_uuid": "102c166f-af2b-4fe2-ade0-ab08063d4d40",
                    "estimated_hours": 0,
                    "content_language_search_facet_name": None,
                    "enterprise_subscription_inclusion": False
                }
            ],
            "entitlements": [
                {
                    "mode": "verified",
                    "price": "149.00",
                    "currency": "USD",
                    "sku": "9023CB5",
                    "expires": None
                }
            ],
            "owners": [
                {
                    "uuid": "2906c944-5698-4e5d-bc18-a2bfe8d343af",
                    "key": "edX",
                    "name": "edX",
                    "auto_generate_course_run_keys": True,
                    "certificate_logo_image_url": None,
                    "logo_image_url": None,
                    "organization_hex_color": None,
                    "description": None,
                    "description_es": "",
                    "homepage_url": None,
                    "tags": [],
                    "marketing_url": "school/edx",
                    "slug": "edx",
                    "banner_image_url": None,
                    "enterprise_subscription_inclusion": False
                }
            ],
            "image": None,
            "short_description": "An introduction to the intellectual enterprises of computer science.",
            "type": "97423c19-8254-43b6-bb7e-33b1f3efe246",
            "url_slug": "introduction-to-computer-science",
            "course_type": "executive-education-2u",
            "enterprise_subscription_inclusion": False,
            "excluded_from_seo": False,
            "excluded_from_search": False,
            "full_description": "This is CS50x , Harvard University's introduction to the ia.",
            "level_type": None,
            "subjects": [],
            "prerequisites": [],
            "prerequisites_raw": "",
            "expected_learning_items": [],
            "video": None,
            "sponsors": [],
            "modified": "2023-05-22T18:02:32.603508Z",
            "marketing_url": None,
            "syllabus_raw": "",
            "outcome": "",
            "original_image": None,
            "card_image_url": None,
            "canonical_course_run_key": "course-v1:edX+DemoX+Demo_Course",
            "extra_description": None,
            "additional_information": "",
            "additional_metadata": {
                "external_identifier": "",
                "external_url": "http://www.edx.org",
                "lead_capture_form_url": "",
                "facts": [],
                "certificate_info": None,
                "organic_url": "",
                "start_date": "2023-01-01T17:29:21Z",
                "end_date": "2023-08-31T17:29:25Z",
                "registration_deadline": "2023-05-31T17:29:42Z",
                "variant_id": None,
                "course_term_override": None,
                "product_status": "published",
                "product_meta": None,
                "external_course_marketing_type": None
            },
            "faq": "",
            "learner_testimonials": "",
            "enrollment_count": 0,
            "recent_enrollment_count": 0,
            "topics": [],
            "key_for_reruns": "",
            "url_slug_history": [
                "introduction-to-computer-science"
            ],
            "url_redirects": [],
            "course_run_statuses": [
                "published"
            ],
            "editors": [],
            "collaborators": [],
            "skill_names": [],
            "skills": [],
            "organization_short_code_override": "",
            "organization_logo_override_url": None,
            "geolocation": None,
            "location_restriction": None,
            "in_year_value": None,
            "product_source": {
                "name": "2u",
                "slug": "2u",
                "description": "2U, Trilogy, Getsmarter -- external source for 2u courses and programs"
            },
            "data_modified_timestamp": "2023-04-10T20:09:07Z",
            "programs": [
                {
                    "uuid": "67147f14-8aa4-492f-a1b3-582e13aa03d5",
                    "title": "edX Demonstration Program",
                    "type": "MicroMasters",
                    "type_attrs": {
                        "uuid": "314d608e-a831-48ce-a92d-9c3d795dc9b3",
                        "slug": "micromasters",
                        "coaching_supported": False
                    },
                    "marketing_slug": "demo-program",
                    "marketing_url": "micromasters/demo-program",
                    "number_of_courses": 1
                }
            ],
            "course_run_keys": [
                "course-v1:edX+DemoX+Demo_Course"
            ],
            "editable": True,
            "advertised_course_run_uuid": "8db5692e-dfdd-4fe0-ba29-e30e793e6ae6"
        },
        {
            "key": "edX+E2E-101",
            "uuid": "990ac8b7-b71d-4db9-9d3b-9805ab2f7f71",
            "title": "Introduction to Cosmology",
            "course_runs": [
                {
                    "key": "course-v1:edX+E2E-101+course",
                    "uuid": "99e43fcd-0442-48c4-a32e-cd657d61907d",
                    "title": "AI Course",
                    "external_key": None,
                    "image": {
                        "src": "http://localhost:18381/media/media/course/image/abc.jpeg",
                        "description": None,
                        "height": None,
                        "width": None
                    },
                    "short_description": "An introduction to programming using Python, a popular language for ia",
                    "marketing_url": "course/ai-course?utm_source=discovery_worker&utm_medium=affiliate_partner",
                    "seats": [
                        {
                            "type": "audit",
                            "price": "0.00",
                            "currency": "USD",
                            "upgrade_deadline": None,
                            "upgrade_deadline_override": None,
                            "credit_provider": None,
                            "credit_hours": None,
                            "sku": "AUDIT_SEAT_123",
                            "bulk_sku": None
                        },
                        {
                            "type": "verified",
                            "price": "149.00",
                            "currency": "USD",
                            "upgrade_deadline": None,
                            "upgrade_deadline_override": None,
                            "credit_provider": None,
                            "credit_hours": None,
                            "sku": "VERIFIED_SEAT_123",
                            "bulk_sku": None
                        }
                    ],
                    "start": "2022-09-11T12:01:08Z",
                    "end": None,
                    "go_live_date": "2022-09-19T09:16:18Z",
                    "enrollment_start": "2022-09-19T09:16:25Z",
                    "enrollment_end": "2022-09-30T09:16:31Z",
                    "weeks_to_complete": 10,
                    "pacing_type": "self_paced",
                    "type": "verified",
                    "run_type": "2d598558-f94e-41f8-8829-01a0027d2d17",
                    "status": "published",
                    "is_enrollable": False,
                    "is_marketable": True,
                    "availability": "Current",
                    "course": "edX+E2E-101",
                    "full_description": "This is CS50x , Harvard University's introduction to the ia",
                    "announcement": None,
                    "video": None,
                    "content_language": "en-us",
                    "license": "",
                    "outcome": "",
                    "transcript_languages": [],
                    "instructors": [],
                    "staff": [],
                    "min_effort": 3,
                    "max_effort": 9,
                    "modified": "2022-10-04T14:02:22.640064Z",
                    "level_type": None,
                    "mobile_available": False,
                    "hidden": False,
                    "reporting_type": "mooc",
                    "eligible_for_financial_aid": True,
                    "first_enrollable_paid_seat_price": 149,
                    "has_ofac_restrictions": None,
                    "ofac_comment": "",
                    "enrollment_count": 0,
                    "recent_enrollment_count": 0,
                    "expected_program_type": None,
                    "expected_program_name": "",
                    "course_uuid": "990ac8b7-b71d-4db9-9d3b-9805ab2f7f71",
                    "estimated_hours": 60.0,
                    "content_language_search_facet_name": "English",
                    "enterprise_subscription_inclusion": True
                }
            ],
            "entitlements": [],
            "owners": [],
            "image": {
                "src": "http://localhost:18381/media/media/course/image/image.jpg",
                "description": None,
                "height": None,
                "width": None
            },
            "short_description": "An introduction to programming using Python, a popular language.",
            "type": "acdf018a-1fa3-4b48-be64-013b447cc03f",
            "url_slug": None,
            "course_type": "verified-audit",
            "enterprise_subscription_inclusion": True,
            "excluded_from_seo": False,
            "excluded_from_search": False,
            "full_description": "This is CS50x , Harvard University's introduction to the ia",
            "level_type": None,
            "subjects": [],
            "prerequisites": [],
            "prerequisites_raw": "",
            "expected_learning_items": [],
            "video": None,
            "sponsors": [],
            "modified": "2022-10-04T14:02:22.446339Z",
            "marketing_url": None,
            "syllabus_raw": "",
            "outcome": "",
            "original_image": {
                "src": "http://localhost:18381/media/media/course/image/image.webp",
                "description": None,
                "height": None,
                "width": None
            },
            "card_image_url": None,
            "canonical_course_run_key": "course-v1:edX+E2E-101+course",
            "extra_description": None,
            "additional_information": "",
            "additional_metadata": None,
            "faq": "",
            "learner_testimonials": "",
            "enrollment_count": 0,
            "recent_enrollment_count": 0,
            "topics": [],
            "key_for_reruns": "",
            "url_slug_history": [],
            "url_redirects": [],
            "course_run_statuses": [
                "published"
            ],
            "editors": [],
            "collaborators": [],
            "skill_names": [],
            "skills": [],
            "organization_short_code_override": "",
            "organization_logo_override_url": None,
            "geolocation": None,
            "location_restriction": None,
            "in_year_value": None,
            "product_source": None,
            "data_modified_timestamp": None,
            "programs": [],
            "course_run_keys": [
                "course-v1:edX+E2E-101+course"
            ],
            "editable": True,
            "advertised_course_run_uuid": "99e43fcd-0442-48c4-a32e-cd657d61907d"
        }
    ]
}
